-- MySQL Script generated by MySQL Workbench
-- Fri Apr 28 00:13:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModuloVentas` ;

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModuloVentas` DEFAULT CHARACTER SET utf8 ;
USE `ModuloVentas` ;

-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_estados` (
  `Pk_id_estado` INT NOT NULL,
  `Descripcion_st` VARCHAR(45) NOT NULL,
  `restriccion_st` INT NOT NULL,
  PRIMARY KEY (`Pk_id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_clientes` (
  `Pk_idCliente` INT NOT NULL,
  `Dpi_cl` VARCHAR(45) NOT NULL,
  `Nombres_cl` VARCHAR(45) NOT NULL,
  `Apellidos_cl` VARCHAR(45) NOT NULL,
  `nit_cl` VARCHAR(45) NOT NULL,
  `estado_cl` INT NOT NULL,
  PRIMARY KEY (`Pk_idCliente`),
  CONSTRAINT `fk_estad_cl`
    FOREIGN KEY (`estado_cl`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_clientes` (`estado_cl` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_pedido` (
  `Pk_idPedido` INT NOT NULL,
  `Fecha_ped` DATETIME NOT NULL,
  `Fk_idcliente_ped` INT NOT NULL,
  PRIMARY KEY (`Pk_idPedido`),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`Fk_idcliente_ped`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_idx` ON `ModuloVentas`.`tbl_pedido` (`Fk_idcliente_ped` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_venta` (
  `Pk_idVenta` INT NOT NULL,
  `Fecha_venta` DATETIME NOT NULL,
  `Total` FLOAT NOT NULL,
  `Fk_pedido` INT NOT NULL,
  PRIMARY KEY (`Pk_idVenta`),
  CONSTRAINT `num_pedido`
    FOREIGN KEY (`Fk_pedido`)
    REFERENCES `ModuloVentas`.`tbl_pedido` (`Pk_idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `num_pedido_idx` ON `ModuloVentas`.`tbl_venta` (`Fk_pedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_factura` (
  `Pk_idFactura` INT NOT NULL,
  `fecha_fac` DATETIME NOT NULL,
  `Descuento_fac` FLOAT NOT NULL,
  `Fk_venta_fac` INT NOT NULL,
  `IVA_fac` FLOAT NOT NULL,
  `Total_fac` FLOAT NOT NULL,
  `Estado_fac` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_idFactura`),
  CONSTRAINT `fk_venta_fac`
    FOREIGN KEY (`Fk_venta_fac`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_venta_fac_idx` ON `ModuloVentas`.`tbl_factura` (`Fk_venta_fac` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_devolucion` (
  `Pk_idDevolucion` INT NOT NULL,
  `Fk_idCliente` INT NOT NULL,
  `Fecha_dev` DATETIME NOT NULL,
  `Nota_cred` INT NOT NULL,
  `No_fac_dev` INT NOT NULL,
  PRIMARY KEY (`Pk_idDevolucion`),
  CONSTRAINT `asdsd`
    FOREIGN KEY (`No_fac_dev`)
    REFERENCES `ModuloVentas`.`tbl_factura` (`Pk_idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `asdsd_idx` ON `ModuloVentas`.`tbl_devolucion` (`No_fac_dev` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_productos` (
  `Pk_idproductos` INT NOT NULL,
  `nombre_produc` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_detalle_venta` (
  `Fk_idventa_detalle` INT NOT NULL,
  `Fk_idproduc_detalle` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_uni` FLOAT NOT NULL,
  `Total_detalle` FLOAT NOT NULL,
  `Estado_venta` VARCHAR(45) NOT NULL,
  CONSTRAINT `venta`
    FOREIGN KEY (`Fk_idventa_detalle`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`Fk_idproduc_detalle`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `venta_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idventa_detalle` ASC) VISIBLE;

CREATE INDEX `producto_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idproduc_detalle` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_almacen` (
  `Pk_idAlmacen` INT NOT NULL,
  `No_almance` INT NOT NULL,
  `Id_producto_al` INT NOT NULL,
  `Cantidad_al` INT NOT NULL,
  PRIMARY KEY (`Pk_idAlmacen`),
  CONSTRAINT `Fk_producto`
    FOREIGN KEY (`Id_producto_al`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Fk_producto_idx` ON `ModuloVentas`.`tbl_almacen` (`Id_producto_al` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_cotizacion` (
  `Pk_idCotizacion` INT NOT NULL,
  `Fk_Idcliente` INT NOT NULL,
  `Fk_detalleVenta` INT NOT NULL,
  PRIMARY KEY (`Pk_idCotizacion`),
  CONSTRAINT `clienteCoti`
    FOREIGN KEY (`Fk_Idcliente`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `clienteCoti_idx` ON `ModuloVentas`.`tbl_cotizacion` (`Fk_Idcliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_contacto_cl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_contacto_cl` (
  `Pk_id_contac` INT NOT NULL,
  `fk_id_cliente_contac` INT NOT NULL,
  `correo_contac` VARCHAR(45) NOT NULL,
  `telefono_contac` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Pk_id_contac`),
  CONSTRAINT `fk_idcliente_contac`
    FOREIGN KEY (`fk_id_cliente_contac`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idcliente_contac_idx` ON `ModuloVentas`.`tbl_contacto_cl` (`fk_id_cliente_contac` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_direccion_cl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_direccion_cl` (
  `Pk_id_direccion` INT NOT NULL,
  `fk_id_cliente_direc` INT NOT NULL,
  `Calle_direc` VARCHAR(15) NOT NULL,
  `Avenida_direc` VARCHAR(15) NOT NULL,
  `Colonia_direc` VARCHAR(45) NOT NULL,
  `Zona_direc` VARCHAR(15) NOT NULL,
  `NumCasa_direc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_id_direccion`),
  CONSTRAINT `fk_cliente_direc`
    FOREIGN KEY (`fk_id_cliente_direc`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_direc_idx` ON `ModuloVentas`.`tbl_direccion_cl` (`fk_id_cliente_direc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_vendedores` (
  `Pk_idVendedor` INT NOT NULL,
  `Dpi_cl` VARCHAR(45) NOT NULL,
  `Nombres_cl` VARCHAR(45) NOT NULL,
  `Apellidos_cl` VARCHAR(45) NOT NULL,
  `estado_cl` INT NOT NULL,
  PRIMARY KEY (`Pk_idVendedor`),
  CONSTRAINT `fk_estad_cl0`
    FOREIGN KEY (`estado_cl`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_vendedores` (`estado_cl` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
