-- MySQL Script generated by MySQL Workbench
-- Tue May  2 09:30:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModuloVentas` ;

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModuloVentas` DEFAULT CHARACTER SET utf8 ;
USE `ModuloVentas` ;

-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_estados` (
  `Pk_id_estado` INT NOT NULL,
  `Descripcion_st` VARCHAR(45) NOT NULL,
  `restriccion_st` INT NOT NULL,
  PRIMARY KEY (`Pk_id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_vendedores` (
  `Pk_idVendedor` INT NOT NULL,
  `Dpi_ven` VARCHAR(45) NOT NULL,
  `Nombres_ven` VARCHAR(45) NOT NULL,
  `Apellidos_ven` VARCHAR(45) NOT NULL,
  `estado_ven` INT NOT NULL,
  `puesto_ven` VARCHAR(25) NOT NULL,
  `nit_ven` VARCHAR(45) NOT NULL,
  `edad_ven` INT NOT NULL,
  PRIMARY KEY (`Pk_idVendedor`),
  CONSTRAINT `fk_estad_cl0`
    FOREIGN KEY (`estado_ven`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_vendedores` (`estado_ven` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_clientes` (
  `Pk_idCliente` INT NOT NULL,
  `Dpi_cl` VARCHAR(45) NOT NULL,
  `Nombres_cl` VARCHAR(45) NOT NULL,
  `Apellidos_cl` VARCHAR(45) NOT NULL,
  `FechaNac_cl` DATE NOT NULL,
  `nit_cl` VARCHAR(45) NOT NULL,
  `estado_cl` INT NOT NULL,
  `direccion_cl` VARCHAR(45) NOT NULL,
  `telefono_cl` VARCHAR(45) NOT NULL,
  `fk_idvendedor` INT NOT NULL,
  PRIMARY KEY (`Pk_idCliente`),
  CONSTRAINT `fk_estad_cl`
    FOREIGN KEY (`estado_cl`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor`
    FOREIGN KEY (`fk_idvendedor`)
    REFERENCES `ModuloVentas`.`tbl_vendedores` (`Pk_idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_clientes` (`estado_cl` ASC) VISIBLE;

CREATE INDEX `fk_vendedor_idx` ON `ModuloVentas`.`tbl_clientes` (`fk_idvendedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_venta` (
  `Pk_idVenta` INT NOT NULL,
  `Sucural_v` VARCHAR(10) NOT NULL,
  `fecha_v` DATETIME NOT NULL,
  `Descuento_v` FLOAT NOT NULL,
  `Fk_venta_v` INT NOT NULL,
  `IVA_v` FLOAT NOT NULL,
  `Total_v` FLOAT NOT NULL,
  `Estado_fac` VARCHAR(45) NOT NULL,
  `fecha_venci_v` DATE NOT NULL,
  `moneda_v` INT NOT NULL,
  `fk_idcliente_v` INT NOT NULL,
  PRIMARY KEY (`Pk_idVenta`, `Sucural_v`),
  CONSTRAINT `idcliente_v`
    FOREIGN KEY (`fk_idcliente_v`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idcliente_v_idx` ON `ModuloVentas`.`tbl_venta` (`fk_idcliente_v` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_devolucion` (
  `Pk_idDevolucion` INT NOT NULL,
  `Fk_idCliente_dev` INT NOT NULL,
  `Fecha_dev` DATETIME NOT NULL,
  `Nota_cred_dev` INT NOT NULL,
  `No_fac_dev` INT NOT NULL,
  PRIMARY KEY (`Pk_idDevolucion`),
  CONSTRAINT `asdsd`
    FOREIGN KEY (`No_fac_dev`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `asdsd_idx` ON `ModuloVentas`.`tbl_devolucion` (`No_fac_dev` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_pedido` (
  `Pk_idPedido` INT NOT NULL,
  `Fecha_ped` DATETIME NOT NULL,
  `Fk_idcliente_ped` INT NOT NULL,
  PRIMARY KEY (`Pk_idPedido`),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`Fk_idcliente_ped`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_idx` ON `ModuloVentas`.`tbl_pedido` (`Fk_idcliente_ped` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_productos` (
  `Pk_idproductos` INT NOT NULL,
  `nombre_produc` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_detalle_venta` (
  `Pk_detalle` INT NOT NULL,
  `Fk_idventa_dv` INT NOT NULL,
  `Fk_idproduc_dv` INT NOT NULL,
  `Cantidad_dv` INT NOT NULL,
  `Precio_uni_dv` FLOAT NOT NULL,
  `Total_dv` FLOAT NOT NULL,
  `Estado_dv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_detalle`),
  CONSTRAINT `producto`
    FOREIGN KEY (`Fk_idproduc_dv`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta`
    FOREIGN KEY (`Fk_idventa_dv`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `producto_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idproduc_dv` ASC) VISIBLE;

CREATE INDEX `venta_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idventa_dv` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_almacen` (
  `Pk_idAlmacen` INT NOT NULL,
  `Nombre_al` VARCHAR(15) NOT NULL,
  `Id_producto_al` INT NOT NULL,
  `estado_al` INT NOT NULL,
  PRIMARY KEY (`Pk_idAlmacen`),
  CONSTRAINT `Fk_producto`
    FOREIGN KEY (`Id_producto_al`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Fk_producto_idx` ON `ModuloVentas`.`tbl_almacen` (`Id_producto_al` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_cotizacion` (
  `Pk_idCotizacion` INT NOT NULL,
  `Fk_Idcliente` INT NOT NULL,
  `Fk_detalleVenta` INT NOT NULL,
  PRIMARY KEY (`Pk_idCotizacion`),
  CONSTRAINT `clienteCoti`
    FOREIGN KEY (`Fk_Idcliente`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `clienteCoti_idx` ON `ModuloVentas`.`tbl_cotizacion` (`Fk_Idcliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_det_Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_det_Cotizacion` (
  `Pk_detalle_coti` INT NOT NULL,
  `Fk_idcoti_c` INT NOT NULL,
  `Fk_idproduc_c` INT NOT NULL,
  `Cantidad_c` INT NOT NULL,
  `Precio_uni_C` FLOAT NOT NULL,
  `Total_detalle_c` FLOAT NOT NULL,
  `Estado_coti` INT NOT NULL,
  PRIMARY KEY (`Pk_detalle_coti`),
  CONSTRAINT `fk_cotizacion`
    FOREIGN KEY (`Fk_idcoti_c`)
    REFERENCES `ModuloVentas`.`tbl_cotizacion` (`Pk_idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cotizacion_idx` ON `ModuloVentas`.`tbl_det_Cotizacion` (`Fk_idcoti_c` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_det_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_det_pedido` (
  `Pk_detalle_ped` INT NOT NULL,
  `Fk_pedido_ped` INT NOT NULL,
  `Fk_idproduc_ped` INT NOT NULL,
  `Cantidad_ped` INT NOT NULL,
  `Precio_uni_ped` FLOAT NOT NULL,
  `Total_ped` FLOAT NOT NULL,
  `Estado_ped` INT NOT NULL,
  PRIMARY KEY (`Pk_detalle_ped`),
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`Fk_pedido_ped`)
    REFERENCES `ModuloVentas`.`tbl_pedido` (`Pk_idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_idx` ON `ModuloVentas`.`tbl_det_pedido` (`Fk_pedido_ped` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
