-- MySQL Script generated by MySQL Workbench
-- Thu May  4 09:33:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModuloVentas` ;

-- -----------------------------------------------------
-- Schema ModuloVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModuloVentas` DEFAULT CHARACTER SET utf8 ;
USE `ModuloVentas` ;

-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_estados` (
  `Pk_id_estados` INT NOT NULL,
  `Descripcion_estados` VARCHAR(45) NOT NULL,
  `restriccion_estados` INT NOT NULL,
  PRIMARY KEY (`Pk_id_estados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_vendedores` (
  `Pk_idVendedores` INT NOT NULL,
  `Dpi_vendedores` VARCHAR(45) NOT NULL,
  `Nombres_vendedores` VARCHAR(45) NOT NULL,
  `Apellidos_vendedores` VARCHAR(45) NOT NULL,
  `estado_vendedores` INT NOT NULL,
  `nit_vendedores` VARCHAR(45) NOT NULL,
  `edad_vendedores` INT NOT NULL,
  PRIMARY KEY (`Pk_idVendedores`),
  CONSTRAINT `fk_estad_cl0`
    FOREIGN KEY (`estado_vendedores`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_vendedores` (`estado_vendedores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_clientes` (
  `Pk_idClientes` INT NOT NULL,
  `Dpi_clientes` VARCHAR(45) NOT NULL,
  `Nombres_clientes` VARCHAR(45) NOT NULL,
  `Apellidos_clientes` VARCHAR(45) NOT NULL,
  `FechaNac_clientes` DATE NOT NULL,
  `nit_clientes` VARCHAR(45) NOT NULL,
  `estado_clientes` INT NOT NULL,
  `direccion_clientes` VARCHAR(45) NOT NULL,
  `telefono_clientes` VARCHAR(45) NOT NULL,
  `fk_idvendedor_clientes` INT NOT NULL,
  `SMesAnterior_clientes` FLOAT NOT NULL,
  `SActual_clientes` FLOAT NOT NULL,
  `CargoMes_clientes` FLOAT NOT NULL,
  `AbonosMes_clientes` FLOAT NOT NULL,
  `CargosAcumulados_clientes` FLOAT NOT NULL,
  `AbonosAcumulados_clientes` FLOAT NOT NULL,
  PRIMARY KEY (`Pk_idClientes`),
  CONSTRAINT `fk_estad_cl`
    FOREIGN KEY (`estado_clientes`)
    REFERENCES `ModuloVentas`.`tbl_estados` (`Pk_id_estados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor`
    FOREIGN KEY (`fk_idvendedor_clientes`)
    REFERENCES `ModuloVentas`.`tbl_vendedores` (`Pk_idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estad_cl_idx` ON `ModuloVentas`.`tbl_clientes` (`estado_clientes` ASC) VISIBLE;

CREATE INDEX `fk_vendedor_idx` ON `ModuloVentas`.`tbl_clientes` (`fk_idvendedor_clientes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_venta` (
  `Pk_idVenta` INT NOT NULL,
  `Sucural_venta` VARCHAR(10) NOT NULL,
  `fecha_venta` DATETIME NOT NULL,
  `Descuento_venta` FLOAT NOT NULL,
  `Fk_venta_venta` INT NOT NULL,
  `IVA_venta` FLOAT NOT NULL,
  `Total_venta` FLOAT NOT NULL,
  `Estado_fac_venta` VARCHAR(45) NOT NULL,
  `fecha_venci_venta` DATE NOT NULL,
  `moneda_venta` INT NOT NULL,
  `fk_idcliente_venta` INT NOT NULL,
  PRIMARY KEY (`Pk_idVenta`, `Sucural_venta`),
  CONSTRAINT `idcliente_v`
    FOREIGN KEY (`fk_idcliente_venta`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idcliente_v_idx` ON `ModuloVentas`.`tbl_venta` (`fk_idcliente_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_devolucion` (
  `Pk_idDevolucion` INT NOT NULL,
  `Fk_idCliente_devolucion` INT NOT NULL,
  `Fecha_devolucion` DATETIME NOT NULL,
  `Nota_cred_devolucion` INT NOT NULL,
  `No_fac_devolucion` INT NOT NULL,
  PRIMARY KEY (`Pk_idDevolucion`),
  CONSTRAINT `asdsd`
    FOREIGN KEY (`No_fac_devolucion`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `asdsd_idx` ON `ModuloVentas`.`tbl_devolucion` (`No_fac_devolucion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_pedido` (
  `Pk_idPedido` INT NOT NULL,
  `sucursal_pedido` VARCHAR(15) NOT NULL,
  `Fecha_pedido` DATETIME NOT NULL,
  `Fk_idcliente_pedido` INT NOT NULL,
  PRIMARY KEY (`Pk_idPedido`, `sucursal_pedido`),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`Fk_idcliente_pedido`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_idx` ON `ModuloVentas`.`tbl_pedido` (`Fk_idcliente_pedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_productos` (
  `Pk_idproductos` INT NOT NULL,
  `nombre_productos` VARCHAR(45) NOT NULL,
  `estado_productos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_detalle_venta` (
  `Pk_Sucursal_detalleventa` VARCHAR(10) NOT NULL,
  `PK_orden_detalleventa` INT NOT NULL,
  `Fk_idventa_detalleventa` INT NOT NULL,
  `Fk_idproduc_detalleventa` INT NOT NULL,
  `Cantidad_detalleventa` INT NOT NULL,
  `Precio_uni_detalleventa` FLOAT NOT NULL,
  `Total_detalleventa` FLOAT NOT NULL,
  `Estado_detalleventa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pk_Sucursal_detalleventa`, `PK_orden_detalleventa`, `Fk_idventa_detalleventa`, `Fk_idproduc_detalleventa`),
  CONSTRAINT `producto`
    FOREIGN KEY (`Fk_idproduc_detalleventa`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta`
    FOREIGN KEY (`Fk_idventa_detalleventa`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Pk_idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sucursal_Det`
    FOREIGN KEY (`Pk_Sucursal_detalleventa`)
    REFERENCES `ModuloVentas`.`tbl_venta` (`Sucural_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `producto_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idproduc_detalleventa` ASC) VISIBLE;

CREATE INDEX `venta_idx` ON `ModuloVentas`.`tbl_detalle_venta` (`Fk_idventa_detalleventa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_almacen` (
  `Pk_idAlmacen` INT NOT NULL,
  `Nombre_almacen` VARCHAR(15) NOT NULL,
  `estado_almacen` INT NOT NULL,
  PRIMARY KEY (`Pk_idAlmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_cotizacion` (
  `Pk_idCotizacion` INT NOT NULL,
  `Sucursal_cotizacion` VARCHAR(15) NOT NULL,
  `Fk_Idcliente_cotizacion` INT NOT NULL,
  `Fk_detalleVenta_cotizacion` INT NOT NULL,
  PRIMARY KEY (`Pk_idCotizacion`, `Sucursal_cotizacion`),
  CONSTRAINT `clienteCoti`
    FOREIGN KEY (`Fk_Idcliente_cotizacion`)
    REFERENCES `ModuloVentas`.`tbl_clientes` (`Pk_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `clienteCoti_idx` ON `ModuloVentas`.`tbl_cotizacion` (`Fk_Idcliente_cotizacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_detalle_Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_detalle_Cotizacion` (
  `Pk_detallecotizacion` INT NOT NULL,
  `Fk_idcoti_detallecotizacion` INT NOT NULL,
  `Fk_idproduc_detallecotizacion` INT NOT NULL,
  `Cantidad_detallecotizacion` INT NOT NULL,
  `Precio_uni_detallecotizacion` FLOAT NOT NULL,
  `Total_detalle_detallecotizacion` FLOAT NOT NULL,
  `Estado_detallecotizacion` INT NOT NULL,
  PRIMARY KEY (`Pk_detallecotizacion`),
  CONSTRAINT `fk_cotizacion`
    FOREIGN KEY (`Fk_idcoti_detallecotizacion`)
    REFERENCES `ModuloVentas`.`tbl_cotizacion` (`Pk_idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cotizacion_idx` ON `ModuloVentas`.`tbl_detalle_Cotizacion` (`Fk_idcoti_detallecotizacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_detalle_pedido` (
  `Pk_detalle_pedido` INT NOT NULL,
  `Fk_pedido_detallepedido` INT NOT NULL,
  `Fk_idproduc_detallepedido` INT NOT NULL,
  `Cantidad_detallepedido` INT NOT NULL,
  `Precio_uni_detallepedido` FLOAT NOT NULL,
  `Total_detallepedido` FLOAT NOT NULL,
  `Estado_detallepedido` INT NOT NULL,
  PRIMARY KEY (`Pk_detalle_pedido`),
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`Fk_pedido_detallepedido`)
    REFERENCES `ModuloVentas`.`tbl_pedido` (`Pk_idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_idx` ON `ModuloVentas`.`tbl_detalle_pedido` (`Fk_pedido_detallepedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ModuloVentas`.`tbl_saldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModuloVentas`.`tbl_saldos` (
  `id_prod_saldos` INT NOT NULL,
  `id_almacen_saldos` INT NOT NULL,
  `saldo_saldos` INT NOT NULL,
  PRIMARY KEY (`id_prod_saldos`, `id_almacen_saldos`),
  CONSTRAINT `producto_exis`
    FOREIGN KEY (`id_prod_saldos`)
    REFERENCES `ModuloVentas`.`tbl_productos` (`Pk_idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `almacen_exis`
    FOREIGN KEY (`id_almacen_saldos`)
    REFERENCES `ModuloVentas`.`tbl_almacen` (`Pk_idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `almacen_exis_idx` ON `ModuloVentas`.`tbl_saldos` (`id_almacen_saldos` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
